#include "config.h"


int CLIENT_MANAGER_PORT = 5220;
int INTERCONNECT_PORT = 6220;
int CLIENT_MANAGER_BACKLOG_LEN = 10;
int CLIENT_SERVICE_ERR_LIMIT = 10;
int MSG_RECEIVER_BACKLOG_LEN = 10;
int TCP_ACCEPT_TIMEOUT = 5;
int TCP_HEADER_TIMEOUT = 1;
int TCP_LOSSABLE_TIMEOUT = 1;
int UDP_PACKET_LEN_LIMIT = 500;
int TCP_PACKET_LEN_LIMIT = 65536;
