#ifndef __DTFS_INTERCMD_H_
#define __DTFS_ITNERCMD_H_

enum InterCommand {
	INT_CMD_UNKNOWN = 0,
	INT_CMD_FIND_NEIGHBOUR,
	INT_CMD_NEIGHBOUR_REPLY,
	INT_CMD_FIND_FILE_BY_NAME,
	INT_CMD_FIND_FILE_BY_NAME_REPLY,
	INT_CMD_FIND_FILE_BY_ID,
	INT_CMD_GET_FILE_INFO,
	INT_CMD_GET_FILE_INFO_REPLY,
	INT_CMD_LOSSABLE_LIMIT = 16384,
};

#endif // __DTFS_ITNERCMD_H_
