#ifndef __DTFS_INTERCMD_H_
#define __DTFS_ITNERCMD_H_

enum InterCommand {
	INT_CMD_UNKNOWN = 0,
	INT_CMD_FIND_NEIGHBOUR,
	INT_CMD_NEIGHBOUR_REPLY,
	INT_CMD_LOSSABLE_LIMIT = 32768,
};

#endif // __DTFS_ITNERCMD_H_
