CXX = g++
CXXFLAGS = -I/usr/local/include/nspr -g
LDFLAGS = -L/usr/local/lib -lnspr4
SRCS = clientmanager.cpp config.cpp clientservice.cpp logger.cpp clientcommand.cpp msgreceiver.cpp
OBJS = clientmanager.o config.o clientservice.o logger.o clientcommand.o msgreceiver.o

all: dfts

dfts: ${OBJS}
	${CXX} ${CXXFLAGS} ${LDFLAGS} ${OBJS} -o $@

clean:
	rm -f ${OBJS} dfts

depend:
	makedepend -- ${CXXFLAGS} -- ${SRCS}
# DO NOT DELETE

clientmanager.o: clientmanager.h /usr/local/include/nspr/prio.h
clientmanager.o: /usr/local/include/nspr/prlong.h
clientmanager.o: /usr/local/include/nspr/prtypes.h
clientmanager.o: /usr/local/include/nspr/prcpucfg.h /usr/include/stddef.h
clientmanager.o: /usr/include/sys/cdefs.h /usr/include/sys/_null.h
clientmanager.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
clientmanager.o: /usr/local/include/nspr/obsolete/protypes.h
clientmanager.o: /usr/include/sys/types.h /usr/include/machine/endian.h
clientmanager.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/select.h
clientmanager.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
clientmanager.o: /usr/include/sys/timespec.h /usr/local/include/nspr/prtime.h
clientmanager.o: /usr/local/include/nspr/prinrval.h
clientmanager.o: /usr/local/include/nspr/prinet.h /usr/include/sys/socket.h
clientmanager.o: /usr/include/sys/_iovec.h /usr/include/machine/param.h
clientmanager.o: /usr/include/netinet/in.h /usr/include/netinet6/in6.h
clientmanager.o: /usr/include/arpa/inet.h /usr/include/netdb.h
clientmanager.o: /usr/include/rpc/types.h /usr/include/sys/time.h
clientmanager.o: /usr/include/time.h /usr/include/netconfig.h
clientmanager.o: /usr/local/include/nspr/prthread.h clientservice.h core.h
clientmanager.o: clientcommand.h config.h threadwrap.h
clientmanager.o: /usr/local/include/nspr/prnetdb.h
config.o: config.h
clientservice.o: clientservice.h /usr/local/include/nspr/prio.h
clientservice.o: /usr/local/include/nspr/prlong.h
clientservice.o: /usr/local/include/nspr/prtypes.h
clientservice.o: /usr/local/include/nspr/prcpucfg.h /usr/include/stddef.h
clientservice.o: /usr/include/sys/cdefs.h /usr/include/sys/_null.h
clientservice.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
clientservice.o: /usr/local/include/nspr/obsolete/protypes.h
clientservice.o: /usr/include/sys/types.h /usr/include/machine/endian.h
clientservice.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/select.h
clientservice.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
clientservice.o: /usr/include/sys/timespec.h /usr/local/include/nspr/prtime.h
clientservice.o: /usr/local/include/nspr/prinrval.h
clientservice.o: /usr/local/include/nspr/prinet.h /usr/include/sys/socket.h
clientservice.o: /usr/include/sys/_iovec.h /usr/include/machine/param.h
clientservice.o: /usr/include/netinet/in.h /usr/include/netinet6/in6.h
clientservice.o: /usr/include/arpa/inet.h /usr/include/netdb.h
clientservice.o: /usr/include/rpc/types.h /usr/include/sys/time.h
clientservice.o: /usr/include/time.h /usr/include/netconfig.h
clientservice.o: /usr/local/include/nspr/prthread.h core.h clientcommand.h
clientservice.o: config.h /usr/include/stdio.h threadwrap.h
clientservice.o: /usr/include/strings.h
logger.o: config.h /usr/include/stdarg.h /usr/include/sys/cdefs.h
logger.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
logger.o: /usr/include/stdio.h /usr/include/sys/_null.h
logger.o: /usr/local/include/nspr/prerror.h /usr/local/include/nspr/prtypes.h
logger.o: /usr/local/include/nspr/prcpucfg.h /usr/include/stddef.h
logger.o: /usr/local/include/nspr/obsolete/protypes.h
logger.o: /usr/include/sys/types.h /usr/include/machine/endian.h
logger.o: /usr/include/sys/_pthreadtypes.h /usr/include/sys/select.h
logger.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
logger.o: /usr/include/sys/timespec.h /usr/local/include/nspr/prerr.h
logger.o: /usr/include/string.h /usr/include/strings.h
clientcommand.o: clientcommand.h
